config/routes.rb
Rails.application.routes.draw do
 
# root to home page
get 'pages/home'
root to: 'pages#home'

# roots to login details
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
delete '/login' => 'sessions#destroy'  

# API / roots for reservations
get '/reservations' => 'reservations#index'

post '/reservations' => 'reservations#create'

get '/flights/json' => 'flights#json' # get json for flights

# User resources 
resources :users
resources :planes
resources :flights

get '/users/:name/json' => 'users#index'

get '/plane/json' => 'planes#json'

get '/flights/:destination/json' => 'flights#index_flight_destination'

get '/flights/:origin/:destination/' =>
'flights#index_flight_search'

end

app/models/flight.rb
class Flight < ApplicationRecord

    belongs_to :plane, optional: true
    has_many :reservations
    has_many :users, through: 'reservations'

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # React frontend, so we wont have this token
  skip_before_action :verify_authenticity_token, raise:false
  
  def json
   headers['Access-Control-Allow-Origin'] = '*'

    @flights = Flight.all 

    render json: @flights, include: [:plane]

  end




  def new

    @flight = Flight.new 
  end

  def create

    @flight = Flight.new flight_params
    @flight.user_id = @current_user.id
    
    # @flight.save

    if @flight.persisted?
      redirect_to flight_path(@flight)
    else
      render :new
    end #else
  end

  def index
    @flights = Flight.all
  end

  def index_flight_destination
    headers['Access-Control-Allow-Origin'] = '*'

    @index_flight_destination = Flight.where destination: params[:destination]

    render json: @index_flight_destination, include: [:plane]
  end

  def index_flight_search
    headers['Access-Control-Allow-Origin'] = '*'

    @index_flight_destination = Flight.where origin: params[:origin], destination: params[:destination]

    render json: @index_flight_destination, include: [:plane, :reservations]
  end

  def show
    @flight = Flight.find params[:id]
   
    render json: @flight, include: [:plane, :reservations]
    # @booking = Booking.new

  end

  def edit
    @flight = Flight.find params[:id]
    
    
    if @flight.user_id != @current_user.id
      redirect_to login_path 
    end

  end

  def update
    @flight = Flight.find params[:id]
    
    # @flight.save

    
    if @flight.user_id != @current_user.id
      redirect_to login_path
      return
      
    end
    
    
    
    
    if @flight.update flight_params
      redirect_to flight_path(@flight)
    else
      render :edit
    end
  end

  def destroy
    @flight = Flight.find params[:id]

    if @flight.user_id != @current_user.id
      redirect_to login_path
      return
    end

    @flight.destroy
    redirect_to flights_path
  end

  


  private
  def flight_params
    params.require(:flight).permit(:flight, :departure_date, :origin, :destination, :seats, :plane_id)
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with model: @flight, local: true, html: { mulipart: true } do |f| %>

<%= f.label :flight%>
<br>
<%= f.number_field :flight %>
<br><br>

<%= f.label :departure_date %>
<br>
<%= f.date_field :departure_date %>
<br><br>

<%= f.label :origin %>
<br>
<%= f.text_field :origin %>
<br><br>

<%= f.label :destination %>
<br>
<%= f.text_field :destination %>
<br><br>

<%= f.label :plane %>
<br>
<%= f.number_field :plane_id %>
<br><br>

<%= f.label :seats %>
<br>
<%= f.number_field :seats %>
<br><br>

<%= f.submit %>

<% end %>

app/views/flights/create.html.erb
<h1>Flights#create</h1>
<p>Find me in app/views/flights/create.html.erb</p>

app/views/flights/destroy.html.erb
<h1>Flights#destroy</h1>
<p>Find me in app/views/flights/destroy.html.erb</p>

app/views/flights/edit.html.erb
<h2>
Edit <%= @flight.flight %></h2>

<%= render partial: 'form' %>

app/views/flights/index.html.erb
<h2>All Flights</h2>

<%= link_to 'Add Flight', new_flight_path %>

<p>
Total: <%= pluralize(@flights.length, 'flight') %>
</p>

    <table>
    <tr>
        <th>Flight</th>
        <th>Date</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Plane</th>
        <th>Remaining Seats</th>
    </tr>
    <% @flights.each do |flight| %>
    <tr>
            <td><%= link_to flight.flight, flight_path(flight) %> </td>
            <td><%= link_to flight.departure_date, flight_path(flight)%></td>
            <td><%= link_to flight.origin, flight_path(flight) %></td>
            <td><%= link_to flight.destination, flight_path(flight) %></td>
            <td><%= link_to flight.plane_id, flight_path(flight) %></td>
            <td><%= link_to flight.seats, flight_path(flight) %></td>
        
    </tr>
    <% end %>
    
    </table>

app/views/flights/new.html.erb
<h2>Add New Flight</h2>

<%= render partial: 'form' %>

app/views/flights/show.html.erb
<h2>
    Flight: <%= @flight.flight %>   
</h2>

<% if @current_user.present? && @current_user.id == @flight.user_id %>
<%= link_to 'Edit', edit_flight_path(@flight) %>
|
<%= link_to 'Delete', flight_path(@flight.id), method: 'delete' %>
<% end %>
<hr>

<table>
    <tr>
        <th>Date</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Plane</th>
        <th>Remaining Seats</th>
    </tr>
    
    <tr>
            
            <td><%= @flight.departure_date %></td>
            <td><%= @flight.origin %></td>
            <td><%= @flight.destination %></td>
            <td><%= @flight.plane_id %></td>
            <td><%= @flight.seats %></td>
        
    </tr>
    

app/views/flights/update.html.erb
<h1>Flights#update</h1>
<p>Find me in app/views/flights/update.html.erb</p>