config/routes.rb
Rails.application.routes.draw do
 
# root to home page
get 'pages/home'
root to: 'pages#home'

# roots to login details
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
delete '/login' => 'sessions#destroy'  

# API / roots for reservations
get '/reservations' => 'reservations#index'

post '/reservations' => 'reservations#create'

get '/flights/json' => 'flights#json' # get json for flights

# User resources 
resources :users
resources :planes
resources :flights

get '/users/:name/json' => 'users#index'

get '/plane/json' => 'planes#json'

get '/flights/:destination/json' => 'flights#index_flight_destination'

get '/flights/:origin/:destination/' =>
'flights#index_flight_search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BurningAirlines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav>
    <header>
       <%# Link to login, singup, edit and delete functions %>
      <div class="login">
          <% if @current_user.present? %>
            Welcome, <%= @current_user.name %>
            |2
            <%= link_to 'LogOut', login_path, method:'delete'%>
            |
            <%= link_to 'Edit Account', edit_user_path(@current_user.id)%>
            |
            <%= link_to 'Profile', user_path(@current_user.id) %> 
            |
            <%# Pop-up message warning users to confirm deleting a profile before proceeding %>
            <%= link_to 'Delete Account', user_path(@current_user.id), method: 'delete', :data => { :confirm => 'Are you sure you want to Delete your account?'} %>
            |
            <%= link_to 'View All Planes', planes_path %>
            |
            <%= link_to 'Create New Planes', new_plane_path %>
            <% else %>
            <%= link_to 'Login', login_path %>
            |
            <%= link_to 'Sign Up', new_user_path %>
          <% end %>
        </div>
    </header>
    <br>
      <h1 class="page-header">MJE AIRWAYS!</h1>
      <p>We only have little seats as we are exclusive</p>


        <div class="nav">
          <%= link_to 'Home', root_path %>
          |
          <%= link_to 'All Flights', flights_path %>
        </div>
    </nav>

    <%= yield %>

    <footer>
    <hr>
    &copy; Secure & Private Blockchain for NFT's
    </footer>
  </body>
</html>